"""Duration-balanced lane partition from recorded per-file durations.

Static suggestion (:mod:`pytest_lanes.suggest`) can only see directories,
so a repo whose tests live in one dominant "misc" directory gets one lane
and no parallelism at all. This module answers the other question: given
what the suite actually *measured* last run, which files should sit in
which lane so the lanes finish at roughly the same time?

The unit of packing is a directory, not a file — directories keep related
tests (and their conftest fixtures) together, and a directory prefix keeps
matching files added later. A directory heavy enough to blow the balance
on its own is the exception: it gets split at file granularity and its
files are listed explicitly.

Everything here is pure and deterministic: the same records produce the
same partition, with no dependence on dict insertion order or hashing.
"""

from __future__ import annotations

import heapq
import re
from collections.abc import Mapping
from dataclasses import dataclass

from pytest_lanes.durations import LaneRecord

_MINIMUM_FILES_TO_BALANCE = 2
# A directory this much heavier than the per-lane target cannot be placed
# without unbalancing the run, so it is split at file granularity instead.
OVERSIZED_DIRECTORY_RATIO = 1.3
# The catch-all lane the formatter always emits; balanced lanes must never
# take this name, or the fallback would lose its own INI section.
REST_LANE_NAME = "rest"
_DEFAULT_LANE_NAME = "lane"


@dataclass(frozen=True)
class BalancedLane:
    name: str
    files: tuple[tuple[str, float], ...]
    projected_seconds: float
    whole_directories: tuple[str, ...]


def balanced_partition(
    records: Mapping[str, LaneRecord],
    lane_count: int,
) -> tuple[BalancedLane, ...]:
    pooled = _pooled_files(records)
    if len(pooled) < _MINIMUM_FILES_TO_BALANCE:
        return ()
    bins_wanted = _clamped_lane_count(lane_count, pooled)
    bins = _longest_processing_time_pack(
        _packing_units(pooled, bins_wanted), bins_wanted
    )
    return _lanes_heaviest_first(bins, pooled)


def format_balanced_suggestion(lanes: tuple[BalancedLane, ...]) -> str:
    """Render the partition as a paste-ready, heavily commented INI block.

    Empty string when there is no partition: printing an empty block
    would read as advice.
    """
    if not lanes:
        return ""

    names = [lane.name for lane in lanes]
    lines = [*_header_lines(lanes), *_markers_block(names), *_index_block(names)]
    for lane in lanes:
        lines.extend(_lane_section(lane))
    lines.extend(_rest_section())
    return "\n".join(lines)


def _header_lines(lanes: tuple[BalancedLane, ...]) -> list[str]:
    recorded_seconds = sum(lane.projected_seconds for lane in lanes)
    recorded_files = sum(len(lane.files) for lane in lanes)
    # Printed output stays ASCII-only: Windows consoles with legacy code
    # pages render non-ASCII punctuation as replacement characters.
    return [
        "# pytest-lanes balanced suggestion - generated by --lanes-suggest from",
        "# recorded per-file durations, not from static analysis.",
        f"# Measured: {recorded_seconds:.1f}s across {recorded_files} files; the",
        "# balance is only as current as that recording.",
        "# Every lane runs in its own subprocess and re-pays environment startup",
        "# (containers, imports, collection) on every run, so more lanes is not",
        "# automatically faster.",
        "# The balance sees durations only, not what tests are coupled to: files",
        "# that talk to the same shared external service (one container, one",
        "# database, one compose project) must be moved into the same lane by",
        "# hand, or the lanes race each other's setup and teardown.",
        "# Review and adjust, then verify the partition with:",
        "#     pytest . --lanes-explain",
        "",
    ]


def _markers_block(names: list[str]) -> list[str]:
    lines = ["[pytest]", "markers ="]
    for name in [*names, REST_LANE_NAME]:
        lines.append(f"    {name}: {name} lane (balanced by pytest-lanes)")
    return lines


def _index_block(names: list[str]) -> list[str]:
    scheduled = " ".join([*names, REST_LANE_NAME])
    return [
        "",
        "[pytest-lanes]",
        f"lanes = {scheduled}",
        f"subprocess_order_standard = {scheduled}",
    ]


def _lane_section(lane: BalancedLane) -> list[str]:
    lines = [
        "",
        f"[pytest-lanes:{lane.name}]",
        f"# projected: {lane.projected_seconds:.1f}s",
        f"marker = {lane.name}",
        # The same assertion config.py demands when it parses this key.
        "# divisible asserts the lane's files are mutually independent AND",
        "# that its environment can run duplicated",
        "divisible = files",
    ]
    if lane.whole_directories:
        prefixes = " ".join(f"{directory}/" for directory in lane.whole_directories)
        lines.append(f"classifier_path_prefixes = {prefixes}")

    listed_files = _files_outside_whole_directories(lane)
    if listed_files:
        lines.append("classifier_paths = " + " ".join(listed_files))

    lines.append(
        "subprocess_paths = " + " ".join([*lane.whole_directories, *listed_files])
    )
    return lines


def _files_outside_whole_directories(lane: BalancedLane) -> tuple[str, ...]:
    """Files a prefix does not already claim - listed one by one."""
    return tuple(
        path
        for path, _ in lane.files
        if not any(
            path.startswith(f"{directory}/") for directory in lane.whole_directories
        )
    )


def _rest_section() -> list[str]:
    return [
        "",
        f"[pytest-lanes:{REST_LANE_NAME}]",
        "# claims every test the lanes above do not - tests added since the",
        "# durations were recorded run here instead of being silently skipped;",
        "# tolerate_no_tests keeps an empty catch-all from failing the run",
        f"marker = {REST_LANE_NAME}",
        "classifier_fallback = true",
        "subprocess_ignore_other_lanes = true",
        "tolerate_no_tests = true",
    ]


def _clamped_lane_count(requested: int, pooled: tuple[tuple[str, float], ...]) -> int:
    """Never plan more bins than there are files to put in them.

    A file is the atomic unit — splitting stops there — so bins beyond the
    file count can only ever come out empty. Callers pass something like
    ``min(os.cpu_count(), 8)``; this is the guard, not the policy.
    """
    return max(1, min(requested, len(pooled)))


@dataclass(frozen=True)
class _PackingUnit:
    """One indivisible chunk of work handed to the bin packer."""

    key: str
    files: tuple[tuple[str, float], ...]
    seconds: float


def _packing_units(
    pooled: tuple[tuple[str, float], ...], lane_count: int
) -> tuple[_PackingUnit, ...]:
    """Directories move whole, unless one is big enough to unbalance the run.

    Keeping a directory together is the conservative choice — sibling
    tests share conftest fixtures, and one prefix keeps claiming files
    added later. A directory heavier than
    ``OVERSIZED_DIRECTORY_RATIO`` times the per-lane target would defeat
    the whole point, so that one is opened up and packed file by file.
    """
    oversized_seconds = OVERSIZED_DIRECTORY_RATIO * _total_seconds(pooled) / lane_count
    units: list[_PackingUnit] = []
    for directory, files in _files_by_directory(pooled):
        directory_seconds = _total_seconds(files)
        if directory_seconds > oversized_seconds:
            units.extend(
                _PackingUnit(key=path, files=((path, seconds),), seconds=seconds)
                for path, seconds in files
            )
        else:
            units.append(
                _PackingUnit(key=directory, files=files, seconds=directory_seconds)
            )
    return tuple(units)


def _longest_processing_time_pack(
    units: tuple[_PackingUnit, ...], lane_count: int
) -> tuple[tuple[tuple[str, float], ...], ...]:
    """Greedy LPT: heaviest unit first, always into the lightest bin.

    LPT is the standard makespan heuristic (no worse than 4/3 of optimal)
    and, unlike anything search-based, it is trivially reproducible — the
    same records always produce the same bins.
    """
    bins: list[list[tuple[str, float]]] = [[] for _ in range(lane_count)]
    loads = [(0.0, index) for index in range(lane_count)]
    heapq.heapify(loads)
    for unit in sorted(units, key=lambda unit: (-unit.seconds, unit.key)):
        load, index = heapq.heappop(loads)
        bins[index].extend(unit.files)
        heapq.heappush(loads, (load + unit.seconds, index))
    return tuple(tuple(sorted(files)) for files in bins)


def _lanes_heaviest_first(
    bins: tuple[tuple[tuple[str, float], ...], ...],
    pooled: tuple[tuple[str, float], ...],
) -> tuple[BalancedLane, ...]:
    """Heaviest lane first — the launch order the executor wants anyway.

    Empty bins are dropped rather than emitted: a declared lane that
    collects nothing fails the run, and asking for more lanes than the
    suite can usefully fill is a normal thing to do.
    """
    filled = [files for files in bins if files]
    ordered = sorted(filled, key=lambda files: (-_total_seconds(files), files[0][0]))
    names = _unique_names(tuple(_lane_name(files) for files in ordered))
    return tuple(
        BalancedLane(
            name=name,
            files=files,
            projected_seconds=_total_seconds(files),
            whole_directories=_whole_directories(files, pooled),
        )
        for name, files in zip(names, ordered)
    )


def _unique_names(preferred: tuple[str, ...]) -> tuple[str, ...]:
    """Number duplicates ``_2``, ``_3`` ... in projected-seconds order.

    ``rest`` starts out taken: the catch-all lane owns that name, and two
    INI sections with the same name would silently merge.
    """
    taken = {REST_LANE_NAME}
    resolved: list[str] = []
    for name in preferred:
        candidate = name
        suffix = 1
        while candidate in taken:
            suffix += 1
            candidate = f"{name}_{suffix}"
        taken.add(candidate)
        resolved.append(candidate)
    return tuple(resolved)


def _whole_directories(
    lane_files: tuple[tuple[str, float], ...],
    pooled: tuple[tuple[str, float], ...],
) -> tuple[str, ...]:
    """Directories this lane can claim by prefix without stealing files.

    A prefix reaches into subdirectories too, so a directory only counts
    as whole when *every* pooled file beneath it — nested ones included —
    landed in this lane. Redundant nested prefixes are dropped: the
    ancestor already covers them. The repository root is never a prefix;
    it would claim the entire suite.
    """
    claimed = {path for path, _ in lane_files}
    candidates = sorted({_parent_directory(path) for path in claimed} - {""})
    whole = {
        directory
        for directory in candidates
        if _pooled_paths_under(directory, pooled) <= claimed
    }
    return tuple(
        directory
        for directory in sorted(whole)
        if not _has_ancestor_in(directory, whole)
    )


def _pooled_paths_under(
    directory: str, pooled: tuple[tuple[str, float], ...]
) -> set[str]:
    return {path for path, _ in pooled if path.startswith(f"{directory}/")}


def _has_ancestor_in(directory: str, directories: set[str]) -> bool:
    ancestor = _parent_directory(directory)
    while ancestor:
        if ancestor in directories:
            return True
        ancestor = _parent_directory(ancestor)
    return False


def _lane_name(files: tuple[tuple[str, float], ...]) -> str:
    heaviest_directory, _ = min(
        _files_by_directory(files),
        key=lambda entry: (-_total_seconds(entry[1]), entry[0]),
    )
    return _marker_safe(_basename(heaviest_directory))


def _marker_safe(basename: str) -> str:
    """Turn a directory name into something usable as a pytest marker.

    The name is written into ``[pytest].markers``, an INI section name and
    a ``-m`` expression, and pytest parses that expression as Python — so
    it has to be an identifier, digits-first names included.
    """
    token = re.sub(r"[^a-zA-Z0-9_]+", "_", basename).strip("_")
    if not token:
        return _DEFAULT_LANE_NAME
    if token[0].isdigit():
        return f"{_DEFAULT_LANE_NAME}_{token}"
    return token


def _files_by_directory(
    files: tuple[tuple[str, float], ...],
) -> tuple[tuple[str, tuple[tuple[str, float], ...]], ...]:
    grouped: dict[str, list[tuple[str, float]]] = {}
    for path, seconds in files:
        grouped.setdefault(_parent_directory(path), []).append((path, seconds))
    return tuple(
        (directory, tuple(sorted(grouped[directory]))) for directory in sorted(grouped)
    )


def _parent_directory(path: str) -> str:
    """Recorded paths are pytest node paths: always ``/``-separated."""
    head, separator, _ = path.rpartition("/")
    return head if separator else ""


def _basename(directory: str) -> str:
    return directory.rpartition("/")[2]


def _total_seconds(files: tuple[tuple[str, float], ...]) -> float:
    return sum(seconds for _, seconds in files)


def _pooled_files(
    records: Mapping[str, LaneRecord],
) -> tuple[tuple[str, float], ...]:
    """Pool every recorded file, keeping the slowest measurement of each.

    A file can appear in more than one lane's record (an overlapping
    classifier, a lane renamed between runs). Keeping the maximum keeps
    the projection conservative: a lane is never planned as lighter than
    it has been observed to be.
    """
    slowest: dict[str, float] = {}
    for record in records.values():
        for path, seconds in record.files:
            slowest[path] = max(slowest.get(path, 0.0), float(seconds))
    return tuple(sorted(slowest.items()))
