"""Static lane-config suggestion for ``--lanes-suggest``."""

from __future__ import annotations

import ast
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from pytest_lanes.adhoc import FALLBACK_LANE_NAME
from pytest_lanes.durations import LaneRecord
from pytest_lanes.layout import (
    has_root_level_test_files,
    test_bearing_subdirectories,
)
from pytest_lanes.sharding import contiguous_halves

_INFRASTRUCTURE_IMPORT_ROOTS = frozenset(
    {
        "testcontainers",
        "docker",
        "psycopg",
        "psycopg2",
        "asyncpg",
        "pymysql",
        "mysql",
        "sqlalchemy",
        "redis",
        "kafka",
        "confluent_kafka",
        "pika",
        "pymongo",
        "boto3",
    }
)
_EXPENSIVE_FIXTURE_SCOPES = frozenset({"session", "package", "module"})


@dataclass(frozen=True)
class DirectoryScan:
    name: str
    infrastructure_imports: tuple[str, ...]
    scoped_fixtures: tuple[str, ...]

    def is_infrastructure_heavy(self) -> bool:
        return bool(self.infrastructure_imports or self.scoped_fixtures)


@dataclass(frozen=True)
class ProjectScan:
    directories: tuple[DirectoryScan, ...]
    has_root_level_tests: bool


def scan_project(rootpath: Path) -> ProjectScan:
    directories = tuple(
        _scan_directory(directory)
        for directory in test_bearing_subdirectories(rootpath)
    )
    return ProjectScan(
        directories=directories,
        has_root_level_tests=has_root_level_test_files(rootpath),
    )


def _scan_directory(directory: Path) -> DirectoryScan:
    imports: list[str] = []
    fixtures: list[str] = []
    for conftest in sorted(directory.rglob("conftest.py")):
        _scan_conftest(conftest, imports, fixtures)
    return DirectoryScan(
        name=directory.name,
        infrastructure_imports=tuple(dict.fromkeys(imports)),
        scoped_fixtures=tuple(dict.fromkeys(fixtures)),
    )


def _scan_conftest(conftest: Path, imports: list[str], fixtures: list[str]) -> None:
    try:
        tree = ast.parse(conftest.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                _note_infrastructure_import(alias.name, imports)
        elif isinstance(node, ast.ImportFrom) and node.module:
            _note_infrastructure_import(node.module, imports)
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and _has_expensive_fixture_decorator(node):
            fixtures.append(node.name)


def _note_infrastructure_import(module_name: str, imports: list[str]) -> None:
    top_level = module_name.split(".")[0]
    if top_level in _INFRASTRUCTURE_IMPORT_ROOTS:
        imports.append(top_level)


def _has_expensive_fixture_decorator(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> bool:
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        is_fixture_call = (
            isinstance(func, ast.Attribute) and func.attr == "fixture"
        ) or (isinstance(func, ast.Name) and func.id == "fixture")
        if not is_fixture_call:
            continue
        for keyword in decorator.keywords:
            if (
                keyword.arg == "scope"
                and isinstance(keyword.value, ast.Constant)
                and keyword.value.value in _EXPENSIVE_FIXTURE_SCOPES
            ):
                return True
    return False


def format_lane_suggestion(scan: ProjectScan) -> str:
    if len(scan.directories) < 2:
        return (
            "# pytest-lanes: no test-bearing subdirectory partition found -\n"
            "# lanes need at least two test directories to run in parallel."
        )

    ordered = _slowest_first_heuristic(scan.directories)
    lane_names = [directory.name for directory in ordered]
    scheduled = list(lane_names)
    if scan.has_root_level_tests:
        scheduled.append(FALLBACK_LANE_NAME)

    # ASCII-only output: legacy Windows code pages mangle anything else.
    lines = [
        "# pytest-lanes suggestion - generated by --lanes-suggest from static",
        "# analysis (directory layout + conftest.py imports and fixture scopes).",
        "# Review and adjust, then verify the partition with:",
        "#     pytest . --lanes-explain",
        "",
        "[pytest]",
        "markers =",
    ]
    for name in [*lane_names, FALLBACK_LANE_NAME]:
        lines.append(f"    {name}: {name} lane (suggested by pytest-lanes)")

    lines += [
        "",
        "[pytest-lanes]",
        f"lanes = {' '.join([*lane_names, FALLBACK_LANE_NAME])}",
        f"subprocess_order_standard = {' '.join(scheduled)}",
    ]

    for directory in ordered:
        lines += ["", f"[pytest-lanes:{directory.name}]"]
        detected = _detected_comment(directory)
        if detected:
            lines.append(detected)
        lines += [
            f"marker = {directory.name}",
            f"classifier_path_prefixes = {directory.name}/",
            f"subprocess_paths = {directory.name}",
        ]

    lines += [
        "",
        f"[pytest-lanes:{FALLBACK_LANE_NAME}]",
        "# claims every test not claimed above; scheduled only when tests",
        "# exist outside the directories listed (an empty lane fails a run)",
        f"marker = {FALLBACK_LANE_NAME}",
        "classifier_fallback = true",
        "subprocess_ignore_other_lanes = true",
    ]

    return "\n".join(lines)


def format_split_advice(records: Mapping[str, LaneRecord]) -> str:
    """Advise splitting the longest recorded lane into two declared lanes."""
    candidate = _longest_splittable_lane(records)
    if candidate is None:
        return ""
    name, record = candidate

    tests_seconds = sum(seconds for _, seconds in record.files)
    fixed_seconds = record.startup + record.collect
    if tests_seconds / 2 <= fixed_seconds:
        return ""

    first_half, second_half = contiguous_halves(record.files)
    lines = [
        "Split advice (from recorded durations)",
        (
            f"{name}: {tests_seconds:.1f}s of tests across "
            f"{len(record.files)} files, {fixed_seconds:.1f}s fixed cost "
            "(startup + collect)"
        ),
        f"  lane 1 (~{_half_seconds(first_half):.1f}s): "
        + " ".join(path for path, _ in first_half),
        f"  lane 2 (~{_half_seconds(second_half):.1f}s): "
        + " ".join(path for path, _ in second_half),
        (
            "  note: each declared lane re-pays the fixed cost every run; "
            "verify any new partition with --lanes-explain"
        ),
    ]
    return "\n".join(lines)


def _longest_splittable_lane(
    records: Mapping[str, LaneRecord],
) -> tuple[str, LaneRecord] | None:
    splittable = [
        (name, record) for name, record in records.items() if len(record.files) >= 2
    ]
    if not splittable:
        return None
    return max(splittable, key=lambda entry: entry[1].total)


def _half_seconds(half: tuple[tuple[str, float], ...]) -> float:
    return sum(seconds for _, seconds in half)


def _slowest_first_heuristic(
    directories: tuple[DirectoryScan, ...],
) -> list[DirectoryScan]:
    """Infrastructure-heavy directories first; queued lanes launch in this order until durations exist."""
    heavy = [d for d in directories if d.is_infrastructure_heavy()]
    light = [d for d in directories if not d.is_infrastructure_heavy()]
    return [*heavy, *light]


def _detected_comment(directory: DirectoryScan) -> str:
    findings: list[str] = []
    if directory.infrastructure_imports:
        findings.append(
            "infrastructure imports: " + ", ".join(directory.infrastructure_imports)
        )
    if directory.scoped_fixtures:
        findings.append(
            "session/module-scoped fixtures: " + ", ".join(directory.scoped_fixtures)
        )
    if not findings:
        return ""
    return "# detected: " + "; ".join(findings)
