"""Static lane-config suggestion for ``--lanes-suggest``.

Reads project structure only — the directory partition plus an AST scan of
each test directory's ``conftest.py`` files for session/module-scoped
fixtures and infrastructure imports (testcontainers, docker, DB drivers).
No user code is executed. The output is a commented ``[pytest-lanes]`` INI
block printed for review: a starting point, not an oracle — the real
fixture-request graph is deliberately out of scope.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

from pytest_lanes.adhoc import (
    FALLBACK_LANE_NAME,
    _contains_test_files,
    _has_root_level_test_files,
    _is_lane_candidate,
)

_INFRASTRUCTURE_IMPORT_ROOTS = frozenset(
    {
        "testcontainers",
        "docker",
        "psycopg",
        "psycopg2",
        "asyncpg",
        "pymysql",
        "mysql",
        "sqlalchemy",
        "redis",
        "kafka",
        "confluent_kafka",
        "pika",
        "pymongo",
        "boto3",
    }
)
_EXPENSIVE_FIXTURE_SCOPES = frozenset({"session", "package", "module"})


@dataclass(frozen=True)
class DirectoryScan:
    name: str
    infrastructure_imports: tuple[str, ...]
    scoped_fixtures: tuple[str, ...]

    def is_infrastructure_heavy(self) -> bool:
        return bool(self.infrastructure_imports or self.scoped_fixtures)


@dataclass(frozen=True)
class ProjectScan:
    directories: tuple[DirectoryScan, ...]
    has_root_level_tests: bool


def scan_project(rootpath: Path) -> ProjectScan:
    directories = tuple(
        _scan_directory(directory)
        for directory in sorted(rootpath.iterdir())
        if directory.is_dir()
        and _is_lane_candidate(directory)
        and _contains_test_files(directory)
    )
    return ProjectScan(
        directories=directories,
        has_root_level_tests=_has_root_level_test_files(rootpath),
    )


def _scan_directory(directory: Path) -> DirectoryScan:
    imports: list[str] = []
    fixtures: list[str] = []
    for conftest in sorted(directory.rglob("conftest.py")):
        _scan_conftest(conftest, imports, fixtures)
    return DirectoryScan(
        name=directory.name,
        infrastructure_imports=tuple(dict.fromkeys(imports)),
        scoped_fixtures=tuple(dict.fromkeys(fixtures)),
    )


def _scan_conftest(conftest: Path, imports: list[str], fixtures: list[str]) -> None:
    try:
        tree = ast.parse(conftest.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                _note_infrastructure_import(alias.name, imports)
        elif isinstance(node, ast.ImportFrom) and node.module:
            _note_infrastructure_import(node.module, imports)
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and _has_expensive_fixture_decorator(node):
            fixtures.append(node.name)


def _note_infrastructure_import(module_name: str, imports: list[str]) -> None:
    top_level = module_name.split(".")[0]
    if top_level in _INFRASTRUCTURE_IMPORT_ROOTS:
        imports.append(top_level)


def _has_expensive_fixture_decorator(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> bool:
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        is_fixture_call = (
            isinstance(func, ast.Attribute) and func.attr == "fixture"
        ) or (isinstance(func, ast.Name) and func.id == "fixture")
        if not is_fixture_call:
            continue
        for keyword in decorator.keywords:
            if (
                keyword.arg == "scope"
                and isinstance(keyword.value, ast.Constant)
                and keyword.value.value in _EXPENSIVE_FIXTURE_SCOPES
            ):
                return True
    return False


def format_lane_suggestion(scan: ProjectScan) -> str:
    if len(scan.directories) < 2:
        return (
            "# pytest-lanes: no test-bearing subdirectory partition found -\n"
            "# lanes need at least two test directories to run in parallel."
        )

    ordered = _slowest_first_heuristic(scan.directories)
    lane_names = [directory.name for directory in ordered]
    scheduled = list(lane_names)
    if scan.has_root_level_tests:
        scheduled.append(FALLBACK_LANE_NAME)

    # Printed output stays ASCII-only: Windows consoles with legacy code
    # pages render non-ASCII punctuation as replacement characters.
    lines = [
        "# pytest-lanes suggestion - generated by --lanes-suggest from static",
        "# analysis (directory layout + conftest.py imports and fixture scopes).",
        "# Review and adjust, then verify the partition with:",
        "#     pytest . --lanes-explain",
        "",
        "[pytest]",
        "markers =",
    ]
    for name in [*lane_names, FALLBACK_LANE_NAME]:
        lines.append(f"    {name}: {name} lane (suggested by pytest-lanes)")

    lines += [
        "",
        "[pytest-lanes]",
        f"lanes = {' '.join([*lane_names, FALLBACK_LANE_NAME])}",
        f"subprocess_order_standard = {' '.join(scheduled)}",
    ]

    for directory in ordered:
        lines += ["", f"[pytest-lanes:{directory.name}]"]
        detected = _detected_comment(directory)
        if detected:
            lines.append(detected)
        lines += [
            f"marker = {directory.name}",
            f"classifier_path_prefixes = {directory.name}/",
            f"subprocess_paths = {directory.name}",
        ]

    lines += [
        "",
        f"[pytest-lanes:{FALLBACK_LANE_NAME}]",
        "# claims every test not claimed above; scheduled only when tests",
        "# exist outside the directories listed (an empty lane fails a run)",
        f"marker = {FALLBACK_LANE_NAME}",
        "classifier_fallback = true",
        "subprocess_ignore_other_lanes = true",
    ]

    return "\n".join(lines)


def _slowest_first_heuristic(
    directories: tuple[DirectoryScan, ...],
) -> list[DirectoryScan]:
    """Infrastructure-heavy directories first — they almost certainly
    dominate wall time, and queued lanes launch in this order until the
    duration cache has real data."""
    heavy = [d for d in directories if d.is_infrastructure_heavy()]
    light = [d for d in directories if not d.is_infrastructure_heavy()]
    return [*heavy, *light]


def _detected_comment(directory: DirectoryScan) -> str:
    findings: list[str] = []
    if directory.infrastructure_imports:
        findings.append(
            "infrastructure imports: " + ", ".join(directory.infrastructure_imports)
        )
    if directory.scoped_fixtures:
        findings.append(
            "session/module-scoped fixtures: " + ", ".join(directory.scoped_fixtures)
        )
    if not findings:
        return ""
    return "# detected: " + "; ".join(findings)
